version: "3.1"
services:

    postgres:
      image: postgres:11.1-alpine
      container_name: starwars-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=starwars
      ports:
        - "8085:5432"

    webserver:
      image: nginx:alpine
      container_name: starwars-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: starwars-php-fpm
      working_dir: /application
      volumes:
        - .:/application
